### ISSUE TITLE
request allowed? xD

### ISSUE THREAD

**Issue by EPuncker** [dastgir/HPM-Plugins#11]
if you are going to accept requests for plugins someday :P I'd like to suggest http://herc.ws/board/files/file/177-soul-link-boost-single-strip-bypass-fcp/

**Comment by dastgir** [comment]
Allowed :p 

It's a nightmare to touch skill functions xD

**Comment by dastgir** [comment]
Another one done: https://github.com/dastgir/HPM-Plugins/commit/64785ac87c9d98048aebd9148f0b2c379f648897

**Comment by moguri85** [comment]
This plugin is working right? i dont see the checks on the link glistering and the other item O_O

**Comment by dastgir** [comment]
I followed the patch provided in first post

**Comment by moguri85** [comment]
Mmmm i see the Soul Link check there and not in the plugin?

**Comment by dastgir** [comment]
:x it seems I copied half....
Will fix it in few hours
