### ISSUE TITLE
ExtendedVending

### ISSUE THREAD

**Issue by yoongjun** [dastgir/HPM-Plugins#15]
Having this issue when making plugins.

ExtendedVending.c:673:32: error: macro "clif_disp_onlyself" requires 3 arguments           , but only 2 given
ExtendedVending.c: In function ‘vending_purchasereq_mod’:
ExtendedVending.c:673: error: ‘clif_disp_onlyself’ undeclared (first use in this            function)
ExtendedVending.c:673: error: (Each undeclared identifier is reported only once
ExtendedVending.c:673: error: for each function it appears in.)
ExtendedVending.c:680:31: error: macro "clif_disp_onlyself" requires 3 arguments           , but only 2 given
make[1]: *** [../../plugins/ExtendedVending.so] Error 1

**Comment by dastgir** [comment]
Thats the required change for new Hercules..
Update your Hercules or use old version of ExtendedVending: https://raw.githubusercontent.com/dastgir/HPM-Plugins/4649e7d4c58463bb8891481afd05d7b1bcbd39b7/src/plugins/ExtendedVending.c

**Comment by yoongjun** [comment]
The older version is giving me this issue


ExtendedVending.c: In function ‘clif_parse_OpenVending_pre’:
ExtendedVending.c:233: warning: cast discards qualifiers from pointer target type
ExtendedVending.c:235: warning: cast discards qualifiers from pointer target type
ExtendedVending.c: In function ‘vending_purchasereq_mod’:
ExtendedVending.c:507: warning: cast discards qualifiers from pointer target type
ExtendedVending.c:508: warning: cast discards qualifiers from pointer target type
ExtendedVending.c:645: warning: cast discards qualifiers from pointer target type
ExtendedVending.c:646: warning: cast discards qualifiers from pointer target type

**Comment by dastgir** [comment]
You need to manually merge half of this patch:
https://github.com/dastgir/HPM-Plugins/commit/30c83c11b50ec3f148ab1678996ec26b16f3b3f7
Only apply changes where "const " is added
