### ISSUE TITLE
[request] Chat with timestamp

### ISSUE THREAD

**Issue by EPuncker** [dastgir/HPM-Plugins#19]
I really liked the [idea of having time stamp](http://herc.ws/board/topic/10266-chat-with-timestamp/) in messages so here is my request/suggestion feel free to do anytime you want, no hurries 👍 and thanks for the great work!

**Comment by dastgir** [comment]
However, the maximum amount of chars will be reduced(as timestamp will take some of the character)

**Comment by dastgir** [comment]
@EPuncker 
https://github.com/dastgir/HPM-Plugins/commit/77760dfdf410661ddabf7b36c85033e38aa3ef3e

**Comment by dastgir** [comment]
FollowUp: https://github.com/dastgir/HPM-Plugins/commit/01319dffc696e146bc89b402060e96db9ca9427b
