### ISSUE TITLE
Error compiling security.c plugin

### ISSUE THREAD

**Issue by VeilsideGX** [dastgir/HPM-Plugins#2]
Hi Dastgir, it says there's no hercules.h. I'm using the latest svn repo of Hercules. Please see attached
![sec](https://cloud.githubusercontent.com/assets/5967371/10240357/5c5f04c4-690d-11e5-91bb-b6a427315516.png)

**Comment by dastgir** [comment]
Hercules.h exists  src/common/ folder.
And it is there in Hercules repo too...

**Comment by VeilsideGX** [comment]
Yes but not sure why it's returning an error. It happens to other plugins too. Can you try this on the latest repo? because I have 2 latest repo and it didn't work on both.

**Comment by dastgir** [comment]
It's surely msvc configuration error.

**Comment by VeilsideGX** [comment]
You mean I did something wrong with the msvc config? can you pls. check if this is still legit http://herc.ws/wiki/Building_HPM_Plugin_for_MSVC 

I just followed everything in there

**Comment by dastgir** [comment]
Not really I meant to blame you....
Its somewhat wrong configuration on Hercules repo, or the guide isn't updated

**Comment by VeilsideGX** [comment]
Been using plugins before and the guide was accurate, worked for me. But not for the latest repo I guess. Probably something has changed... :( That means we can't compile with MSVC?

**Comment by dastgir** [comment]
Change AdditionalIncludeDir of your Plugin Project to "..\src;..\3rdparty;..\3rdparty\msinttypes\include"
