### ISSUE TITLE
chat_timestamp compilation 2

### ISSUE THREAD

**Issue by SamuelHercules** [dastgir/HPM-Plugins#22]
[see](https://github.com/dastgir/HPM-Plugins/commit/c50cdae5760db8f4b6ef38deb7112e126f7c529c#commitcomment-18270011)

[see2](https://github.com/dastgir/HPM-Plugins/commit/c50cdae5760db8f4b6ef38deb7112e126f7c529c#commitcomment-18270017)

**Comment by dastgir** [comment]
I believe , it's fixed
