### ISSUE TITLE
pk bug

### ISSUE THREAD

**Issue by will21** [dastgir/HPM-Plugins#24]
still hitting enemy when pk is off on pvp map

im using latest pk and latest hercules please fix

**Comment by dastgir** [comment]
If both are in pkmode , it would hit them .
If it's PvP map, it's normal behavior that one can attack to other.
So I guess this is something intended.
Please reopen the issue if I misunderstood you.
Thanks :)

**Comment by will21** [comment]
I have pk server and I want to disable hitting player with pk off state.

Example:
Player A: PK is on
Player B: PK is off

Result:
Player A can't attack Player B because the pk is off status including in pvp maps
