### ISSUE TITLE
hit-delay bug

### ISSUE THREAD

**Issue by will21** [dastgir/HPM-Plugins#25]
go thor_v03 try to died by monster after you died click char select not go still hitting the mob over in over.

**Comment by dastgir** [comment]
Related to #13

**Comment by dastgir** [comment]
Will be fixed in upcoming days

**Comment by will21** [comment]
Thank you! How about pk mode? I replied to your comment https://github.com/dastgir/HPM-Plugins/issues/24

**Comment by will21** [comment]
About your pkmode

I have pk server and I want to disable hitting player with pk off state.

Example:
Player A: PK is on
Player B: PK is off

Result:
Player A can't attack Player B because the pk is off status including in pvp maps

**Comment by dastgir** [comment]
#31 should fix it
