### ISSUE TITLE
sc_itemscript

### ISSUE THREAD

**Issue by flokicrowbr** [dastgir/HPM-Plugins#29]
i found a problem when compiling

17>  sc_itemscript.c
17>..\src\plugins\sc_itemscript.c(59): error C2065: 'SC_DRESS_UP' : undeclared identifier
17>..\src\plugins\sc_itemscript.c(60): error C2065: 'SC_DRESS_UP' : undeclared identifier
17>..\src\plugins\sc_itemscript.c(70): error C2065: 'SC_DRESS_UP' : undeclared identifier
17>..\src\plugins\sc_itemscript.c(71): error C2065: 'SC_DRESS_UP' : undeclared identifier

**Comment by dastgir** [comment]
Update your Hercules (that status was included 2 months ago)
