### ISSUE TITLE
Extended Vending no enabled with feature.conf

### ISSUE THREAD

**Issue by OmarAcero** [dastgir/HPM-Plugins#39]
The plugin is not reading the configuration of the feature.conf file. The only way that the plugin works is when the following lines are edited:

Is lines:
`int bc_extended_vending;`
`int` bc_show_item_vending;
`int` bc_ex_vending_info;
`int` bc_item_zeny;
`int` bc_item_cash;`

Replace For:
`int bc_extended_vending = 1; // Enable Extended Vending System`
`int bc_show_item_vending = 1; // Show Currency Name in the Pub of Vending`
`int bc_ex_vending_info = 1; // Show Information about buying`
`int bc_item_zeny = 30000; // ItemID for Zeny, 0 to disable`
`int bc_item_cash = 30001; // ItemID for CashPoints, 0 to disable`

Note: [Here](http://herc.ws/board/topic/13664-enable-extended-vending-plugin/)

**Comment by dastgir** [comment]
You need to put these in import folder
Under "battle_configuration:"
You can have it either in import or battle.conf/player.conf
Or if you want to put in features, don't put inside "features:" block, put it at end after that block ends.
