### ISSUE TITLE
Error on market plugin

### ISSUE THREAD

**Issue by VeilsideGX** [dastgir/HPM-Plugins#4]
Hi Dastgir,

After a successful compile of the market plugin and then starting the server, I got this error. Please see attached. 
![market-error 2](https://cloud.githubusercontent.com/assets/5967371/10357336/bff08d8c-6db3-11e5-96bd-827f32ce96dd.png)

**Comment by dastgir** [comment]
Clean Recompile Server and Plugin.
that should solve this problem...

**Comment by VeilsideGX** [comment]
This solved the problem. Thanks :)
