### ISSUE TITLE
Compile error on auraset

### ISSUE THREAD

**Issue by VeilsideGX** [dastgir/HPM-Plugins#5]
Hi Dastgir,

I'm using the most recent svn repo. I got this error while compiling the auraset plugin.
![auraset-error](https://cloud.githubusercontent.com/assets/5967371/10357534/b6b3a7c0-6db5-11e5-8da5-9e70b50100fc.png)

**Comment by VeilsideGX** [comment]
I replaced sscanf with sscanf_s and it compiled successfully without any error or warnings. Is that safe to do? would that make any difference on its functionality? x)

**Comment by dastgir** [comment]
Its Visual Studio setting, which (I don't remember correctly) but was strict compiling or something like that,
changing setting to minimal warnings would remove this error.
