### ISSUE TITLE
sscanf and _snprintf warnings on whosell.c

### ISSUE THREAD

**Issue by VeilsideGX** [dastgir/HPM-Plugins#6]
Is it ok to replace sscanf with sscanf_s and _snprintf with _snprintf_s to prevent this warning message? would it make any difference on the functionality?
![whosell-warning](https://cloud.githubusercontent.com/assets/5967371/10388893/5c802bf2-6ea0-11e5-8144-d51843e470b8.png)

Thanks!

**Comment by dastgir** [comment]
Same as #5
