### ISSUE TITLE
Must change malloc.h to memmgr.h

### ISSUE THREAD

**Issue by VeilsideGX** [dastgir/HPM-Plugins#7]
Hercules commit reference: https://github.com/HerculesWS/Hercules/commit/54d1c8b93adbeee5838b8dadabeb789b9fa6c511

Compile error on malloc.h

**Comment by dastgir** [comment]
Yes, Done in https://github.com/dastgir/HPM-Plugins/commit/2a1f916bb0aa80babb87e89c46e5f855012f7c69
Was too busy recently , that's why it got delayed a little bit.
